---
abstract: 'Compute USDX (US Dollar Index)'
author:
  - 'Alberto Simões <ambs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-USDX
no_index:
  directory:
    - t
    - inc
requires:
  Finance::Quote: 1.18
  Test::More: 0
  parent: 0
version: 0.02
